# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-05 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='like_users',
            new_name='liked_users',
        ),
    ]
